exoral/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'exoral'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('downvote/<int:frage_id>', views.FrageDownvote.as_view(), name='downvote-frage'),
    path('dozent/<int:dozent_id>', views.DozentDetail.as_view(), name='dozent-detail'),
    path('dozent/<int:dozent_id>/edit', views.DozentEdit.as_view(), name='dozent-edit'),
    path('dozent/create', views.DozentCreate.as_view(), name='dozent-create'),
    path('dozenten', views.DozentList.as_view(), name='dozent-list'),
    path('fach/<int:fach_id>/edit', views.FachEdit.as_view(), name='fach-edit'),
    path('fach/create', views.FachCreate.as_view(), name='fach-create'),
    path('faecher', views.FachList.as_view(), name='fach-list'),
    path('frage/<int:frage_id>/delete', views.FrageDelete.as_view(), name='frage-delete'),
    path('frage/<int:frage_id>/edit', views.FrageEdit.as_view(), name='frage-edit'),
    path('frage/<int:testat_id>/<int:pruefer_id>/create', views.FrageCreate.as_view(), name='frage-create'),
    path('fragen/<int:testat_id>/<int:pruefer_id>', views.FrageList.as_view(), name='frage-list'),
    path('testat/<int:testat_id>', views.TestatDetail.as_view(), name='testat-detail'),
    path('testat/<int:testat_id>/edit', views.TestatEdit.as_view(), name='testat-edit'),
    path('testat/create', views.TestatCreate.as_view(), name='testat-create'),
    path('testate', views.TestatList.as_view(), name='testat-list'),
    path('upvote/<int:frage_id>', views.FrageUpvote.as_view(), name='upvote-frage'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

exoral/models.py
from django.db import models
from django.conf import settings
from datetime import date

from fsmedhro_core.models import Studienabschnitt, Studiengang


class Fach(models.Model):
    """
    Ein Fach besteht nur aus dem Namen des Fachs, z.B. Anatomie, Biochemie,
    Physiologie.
    """

    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Fach"
        verbose_name_plural = "Fächer"
        ordering = ("name",)

    def __str__(self):
        return self.name

    def admin_list_dozent(self):
        return ', '.join(doz.nachname for doz in self.dozent_set.all())
    admin_list_dozent.short_description = 'Dozenten'


class Dozent(models.Model):
    """
    Nachname, Fach und aktiv sind zwingend erforderlich.
    Titel und Vorname sind optional.

    Ein Dozent ist immer genau einem Fach zugeordnet.
    """

    titel = models.CharField(max_length=30, blank=True)
    vorname = models.CharField(max_length=60, blank=True)
    nachname = models.CharField(max_length=100)
    aktiv = models.BooleanField(default=True)

    fach = models.ForeignKey(Fach, on_delete=models.CASCADE, blank=True)

    class Meta:
        verbose_name = "Dozent"
        verbose_name_plural = "Dozenten"
        ordering = ("nachname",)

    def name(self):
        """
        [Vorname] [Nachname]
        """
        if self.vorname:
            return f"{self.vorname} {self.nachname}"
        else:
            return self.nachname

    def full_name(self):
        """
        [Titel] [Vorname] [Nachname]
        """
        r = self.nachname

        if self.vorname:
            r = f"{self.vorname} {r}"
        if self.titel:
            r = f"{self.titel} {r}"

        return r

    full_name.short_description = "Name"

    def __str__(self):
        return self.full_name()


class Testat(models.Model):
    """
    Ein Testat hat einen Namen und ist aktiv oder nicht.

    Ein Testat kann verschiedenen Studiengängen zugeordnet werden (z.B. Human-
    und Zahnmedizin).
    Ein Testat kann verschiedenen Studienabschnitten zugeordnet werden (z.B. BP
    Chirurgie im 9. und 10. Semester).
    Ein Testat kann verschiedenen Fächern zugeordnet werden (z.B. das Physikum
    den Fächern Anatomie, Biochemie und Physiologie).
    """

    name = models.CharField(max_length=100)
    active = models.BooleanField(default=True)

    fach = models.ManyToManyField(Fach)
    studiengang = models.ManyToManyField(Studiengang)
    studienabschnitt = models.ManyToManyField(Studienabschnitt)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Testat"
        verbose_name_plural = "Testate"
        ordering = ("name",)

    def admin_list_fach(self):
        return ', '.join(fach.name for fach in self.fach.all())
    admin_list_fach.short_description = 'Fächer'

    def admin_list_studiengang(self):
        return ', '.join(studgang.bezeichnung for studgang in self.studiengang.all())
    admin_list_studiengang.short_description = 'Studiengänge'

    def admin_list_studienabschnitt(self):
        return ', '.join(studab.bezeichnung for studab in self.studienabschnitt.all())
    admin_list_studienabschnitt.short_description = 'Studienabschnitte'


class Frage(models.Model):
    datum = models.DateField(default=date.today, verbose_name="Prüfungsdatum")
    text = models.TextField()
    antwort = models.TextField(blank=True)
    punkte = models.PositiveIntegerField(default=1)

    pruefer = models.ForeignKey(
        Dozent,
        on_delete=models.CASCADE,
        verbose_name="PrüferIn",
    )
    testat = models.ForeignKey(
        Testat,
        on_delete=models.CASCADE,
        verbose_name="Testat/Prüfung",
    )
    abgestimmte_benutzer = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
    )

    def __str__(self):
        t = ' '.join(self.text.split()[:10])
        if len(self.text) > len(t):
            t += ' […]'
        return t

    class Meta:
        verbose_name = "Frage"
        verbose_name_plural = "Fragen"

    def upvote(self, user):
        if user not in self.abgestimmte_benutzer.all():
            self.abgestimmte_benutzer.add(user)
            self.punkte = models.F("punkte") + 1
            self.save()

    def downvote(self, user):
        if user in self.abgestimmte_benutzer.all():
            self.abgestimmte_benutzer.remove(user)
            self.punkte = models.F("punkte") - 1
            self.save()

exoral/templates/exoral/dozent_create.html
{% extends "exoral/base.html" %}

{% block content %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:home' %}">Start</a></li>
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:dozent-list' %}">Dozenten</a></li>
      <li class="breadcrumb-item active" aria-current="page">hinzufügen</li>
    </ol>
  </nav>

  {% include "exoral/dozent_form.html" %}
</div>
{% endblock content %}

exoral/templates/exoral/dozent_detail.html
{% extends "exoral/base.html" %}

{% load static %}

{% block content %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:home' %}">Start</a></li>
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:dozent-list' %}">Dozenten</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ dozent }}</li>
      {% if perms.exoral.change_dozent %}
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:dozent-edit' dozent.id %}">bearbeiten</a></li>
      {% endif %}
    </ol>
  </nav>

  <table class="table">
    <tbody>
      <tr>
        <th>Titel</th>
        <td>{{ dozent.titel }}</td>
      </tr>
      <tr>
        <th>Name</th>
        <td>{{ dozent.name }}</td>
      </tr>
      <tr>
        <th>Fach</th>
        <td>{{ dozent.fach }}</td>
      </tr>
      <tr>
        <th>aktiv?</th>
        <td>{% if dozent.aktiv %}✓{% else %}✗{% endif %}</td>
      </tr>
    </tbody>
  </table>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Datum</th>
        <th>Frage</th>
        <th><img src="{% static "img/icons/plus-square.svg" %}"></th>
        <th>Fach</th>
      </tr>
    </thead>
    <tbody>
      {% for frage in dozent.frage_set.all %}
      <tr>
        <td>{{ frage.datum }}</td>
        <td style="white-space: pre-line;">{{ frage.text }}
          {% if perms.exoral.change_frage %}<a href="{% url 'exoral:frage-edit' frage.id %}">bearbeiten</a>{% endif %}
        </td>
        <td>{{ frage.punkte }}</td>
        <td>{{ frage.testat }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

exoral/templates/exoral/dozent_edit.html
{% extends "exoral/base.html" %}

{% block content %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:home' %}">Start</a></li>
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:dozent-list' %}">Dozenten</a></li>
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:dozent-detail' dozent.id %}">{{ dozent }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">bearbeiten</li>
    </ol>
  </nav>

  {% include "exoral/dozent_form.html" %}

  <div class="row">
    <div class="col">
      <div class="alert alert-danger">
        Wenn du den Dozenten löschen willst, dann erledige das <a class="alert-link" target="_blank" href="{% url 'admin:exoral_dozent_change' dozent.id %}">über die Admin-Oberfläche</a>.
        {% if not user.is_staff %}
        Dafür musst du von einem Administrator den <em>Mitarbeiter-Status</em> erhalten. Wende dich an die Admins, damit sie dir das Häkchen setzen.
        {% endif %}
        Bedenke, dass beim Löschen eines Dozenten auch alle dazugehörigen Fragen gelöscht werden. In der Admin-Oberfläche siehst du genau, was dazu gelöscht wird.
      </div>
    </div>
  </div>
</div>
{% endblock content %}

exoral/templates/exoral/dozent_form.html
  <form method="post">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col">
        <label for="id_titel"><strong>Titel</strong></label>
        <input type="text" class="form-control" id="id_titel" name="titel" value="{{ dozent.titel }}">
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col">
        <label for="id_vorname"><strong>Vorname</strong></label>
        <input type="text" class="form-control" id="id_vorname" name="vorname" value="{{ dozent.vorname }}">
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col">
        <label for="id_nachname"><strong>Nachname</strong></label>
        <input type="text" class="form-control" id="id_nachname" name="nachname" value="{{ dozent.nachname }}" required>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col">
        <label for="id_fach"><strong>Fach</strong></label>
        <select name="fach" id="id_fach" class="custom-select" required>
          {% for fach in faecher %}
          <option value="{{ fach.id }}"{% if dozent.fach == fach %} selected{% endif %}>{{ fach }}</option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="form-group form-check">
      <input type="checkbox" class="form-check-input" id="id_aktiv" name="aktiv"{% if dozent.aktiv %} checked{% endif %}>
      <label class="form-check-label" for="id_aktiv">ist aktiv</label>
    </div>
    <div class="form-row">
      <div class="form-group col">
        <input type="submit" class="btn btn-primary" value="Speichern">
      </div>
    </div>
  </form>

exoral/templates/exoral/error.html
{% extends "exoral/base.html" %}

{% block content %}
<div class="container">
  <div class="p-3 mb-2 bg-danger text-white">{{ error }}</div>
</div>
{% endblock content %}

exoral/templates/exoral/fach_create.html
{% extends "exoral/base.html" %}

{% block content %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:home' %}">Start</a></li>
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:fach-list' %}">Fächer</a></li>
      <li class="breadcrumb-item active" aria-current="page">hinzufügen</li>
    </ol>
  </nav>

  {% include "exoral/fach_form.html" %}
</div>
{% endblock content %}

exoral/templates/exoral/fach_edit.html
{% extends "exoral/base.html" %}

{% block content %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:home' %}">Start</a></li>
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:fach-list' %}">Fächer</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ fach }}</li>
    </ol>
  </nav>

  {% include "exoral/fach_form.html" %}

  <div class="row">
    <div class="col">
      <div class="alert alert-danger">
        Wenn du das gesamte Fach löschen willst, dann erledige das <a class="alert-link" target="_blank" href="{% url 'admin:exoral_fach_change' fach.id %}">über die Admin-Oberfläche</a>.
        {% if not user.is_staff %}
        Dafür musst du von einem Administrator den <em>Mitarbeiter-Status</em> erhalten. Wende dich an die Admins, damit sie dir das Häkchen setzen.
        {% endif %}
        Bedenke, dass beim Löschen eines Fachs auch alle dazugehörigen Dozenten und Fragen gelöscht werden. In der Admin-Oberfläche siehst du genau, was dazu gelöscht wird.
      </div>
    </div>
  </div>
</div>
{% endblock content %}

exoral/templates/exoral/fach_form.html
  <form method="post">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col">
        <label for="id_name"><strong>Name</strong></label>
        <input type="text" class="form-control" id="id_name" name="name" value="{{ fach.name }}" required>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col">
        <input type="submit" class="btn btn-primary" value="Speichern">
      </div>
    </div>
  </form>

exoral/templates/exoral/fach_list.html
{% extends "exoral/base.html" %}

{% block content %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:home' %}">Start</a></li>
      <li class="breadcrumb-item active" aria-current="page">Fächer</li>
      {% if perms.exoral.add_fach %}
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:fach-create' %}">hinzufügen</a></li>
      {% endif %}
    </ol>
  </nav>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Dozenten</th>
        <th>Testate</th>
      </tr>
    </thead>
    <tbody>
      {% for fach in fach_list %}
      <tr>
        <td>
          {% if perms.exoral.change_fach %}
          <a href="{% url 'exoral:fach-edit' fach.id %}">{{ fach.name }}</a>
          {% else %}
          {{ fach.name }}
          {% endif %}
        </td>
        <td>
          {% for dozent in fach.dozent_set.all %}
          <a href="{% url 'exoral:dozent-detail' dozent.id %}">{{ dozent }}</a>{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </td>
        <td>
          {% for testat in fach.testat_set.all %}
          <a href="{% url 'exoral:testat-detail' testat.id %}">{{ testat }}</a>{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

exoral/templates/exoral/frage_form.html
{% extends "exoral/base.html" %}

{% load static sekizai_tags %}

{% block js %}
{% addtoblock "js" %}
<script charset="utf-8" src="{% static 'js/helpers.js' %}"></script>
<script charset="utf-8" type="text/javascript">
  function setup() {
    $("#fragentext").keyup(function() {
      var v = $(this).val();

      if (v == '') {
        $(".vorhandene_frage").hide();
      } else {
        filter(
          ".vorhandene_frage",
          v,
          elem => { $(elem).show(); },
          elem => { $(elem).hide(); }
        );
      }

      if ($("p.vorhandene_frage").is(":visible")) {
        $("#warnung_vorhandene_fragen").show();
      } else {
        $("#warnung_vorhandene_fragen").hide();
      }
    });
  }

  $(document).ready(setup);
</script>
{% endaddtoblock %}
{% endblock %}

{% block content %}
<div class="container">
  <div class="alert alert-danger" role="alert">
    Bevor du eine neue Frage hinzufügst, vergewissere dich, ob sie <strong>wirklich</strong> neu ist.
    Bereits vorhandenen Fragen kannst du Pluspunkte geben.<br />
    Bitte füge immer nur eine neue Frage hinzu. Gib mehrere Fragen als separate neue Fragen ein.
  </div>

  <form method="post">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-2">
        <label for="datum"><strong>Datum</strong></label>
        <input type="date" class="form-control" id="datum" name="datum" value="{% now 'Y-m-d' %}" required>
      </div>
      <div class="form-group col-md-5">
        <label for="pruefer"><strong>Prüfer:in</strong></label>
        <input class="form-control" type="text" placeholder="{{ pruefer }}" readonly>
      </div>
      <div class="form-group col-md-5">
        <label for="testat"><strong>Testat</strong></label>
        <input class="form-control" type="text" placeholder="{{ testat }}" readonly>
      </div>
    </div>
    <div class="form-group">
      <label for="fragentext"><strong>Frage</strong></label>
      <textarea class="form-control" id="fragentext" name="text" rows=3 required></textarea>
    </div>
    <div id="vorhandene_fragen">
      <div id="warnung_vorhandene_fragen" style="display: none;" class="alert alert-danger" role="alert">
        Anscheinend existieren schon Fragen, die diesen Text enthalten. Bitte überprüfe, ob diese Frage <strong>wirklich, wirklich</strong> neu ist!
      </div>
      {% for frage in vorhandene_fragen %}
      <p class="vorhandene_frage" style="display: none;">{{ frage.text }}</p>
      {% endfor %}
    </div>
    <div class="form-group">
      <label for="antwort">Antwort</label>
      <textarea class="form-control" id="antwort" name="antwort" rows=3></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Erstellen</button>
  </form>
</div>
{% endblock content %}

exoral/templates/exoral/profil_unvollstaendig.html
{% extends "exoral/base.html" %}

{% block content %}
<div class="container">
  <p>
    Hallo {{ name }},<br>
    leider ist dein Profil noch unvollständig.
    Bitte <a href="{% url 'fsmedhro_core:edit' %}" target="_blank">aktualisiere
    deinen Studiengang und deinen Studienabschnitt</a>, damit wir die zu dir passenden Testate anzeigen können.
  </p>
</div>
{% endblock content %}

exoral/templates/exoral/testat_detail.html
{% extends "exoral/base.html" %}

{% block content %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:home' %}">Start</a></li>
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:testat-list' %}">Testate</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ testat }}</li>
      {% if perms.exoral.change_testat %}
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:testat-edit' testat.id %}">bearbeiten</a></li>
      {% endif %}
    </ol>
  </nav>

  <table class="table">
    <tbody>
      <tr>
        <th>Name</th>
        <td>{{ testat.name }}</td>
      </tr>
      <tr>
        <th>aktiv?</th>
        <td>{% if testat.active %}✓{% else %}✗{% endif %}</td>
      </tr>
      <tr>
        <th>Fächer</th>
        <td>{{ testat.fach.all|join:", " }}</td>
      </tr>
      <tr>
        <th>Studiengänge</th>
        <td>{{ testat.studiengang.all|join:", " }}</td>
      </tr>
      <tr>
        <th>Studienabschnitt</th>
        <td>{{ testat.studienabschnitt.all|join:", " }}</td>
      </tr>
    </tbody>
  </table>

  {% for fach, dozenten in faecher.items %}
  <h4>{{ fach }}</h4>
  <table class="table table-striped">
    <thead>
      <tr>
        <th style="width: 80%;">Prüfer:in</th>
        <th style="width: 20%;">Anzahl Fragen</th>
      </tr>
    </thead>
    <tbody>
    {% for dozent, anz_fragen in dozenten.items %}
      <tr>
        <td><a href="{% url 'exoral:frage-list' testat.pk dozent.pk %}">{{ dozent }}</a></td>
        <td>{{ anz_fragen }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% empty %}
  <p>
    Keine Fächer eingetragen. Wende dich an den FSR, damit Fächer eingetragen werden.
  </p>
  {% endfor %}
</div>
{% endblock content %}

exoral/templates/exoral/testat_form.html
  <form method="post">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col">
        <label for="id_name"><strong>Name</strong></label>
        <input type="text" class="form-control" id="id_name" name="name" value="{{ testat.name }}" required>
      </div>
    </div>
    <div class="form-group form-check">
      <input type="checkbox" class="form-check-input" id="id_active" name="active"{% if testat.active %} checked{% endif %}>
      <label class="form-check-label" for="id_active">ist aktiv</label>
    </div>
    <div class="form-group">
      <label for="id_fach">Fächer</label>
      <select class="form-control" id="id_fach" name="fach" multiple required>
        {% for fach in faecher %}
        <option value="{{ fach.id }}" {% if fach in testat.fach.all %}selected{% endif %}>{{ fach }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label for="id_studiengang">Studiengänge</label>
      <select class="form-control" id="id_studiengang" name="studiengang" multiple required>
        {% for studiengang in studiengaenge %}
        <option value="{{ studiengang.id }}" {% if studiengang in testat.studiengang.all %}selected{% endif %}>{{ studiengang }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label for="id_studienabschnitt">Studienabschnitte</label>
      <select class="form-control" id="id_studienabschnitt" name="studienabschnitt" multiple required>
        {% for studienabschnitt in studienabschnitte %}
        <option value="{{ studienabschnitt.id }}" {% if studienabschnitt in testat.studienabschnitt.all %}selected{% endif %}>{{ studienabschnitt }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-row">
      <div class="form-group col">
        <input type="submit" class="btn btn-primary" value="Speichern">
      </div>
    </div>
  </form>

exoral/templates/exoral/testat_list.html
{% extends "exoral/base.html" %}

{% block content %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:home' %}">Start</a></li>
      <li class="breadcrumb-item active" aria-current="page">Testate</li>
      {% if perms.exoral.add_testat %}
      <li class="breadcrumb-item" aria-current="page"><a href="{% url 'exoral:testat-create' %}">hinzufügen</a></li>
      {% endif %}
    </ol>
  </nav>

  <table class="table table-striped">
    <thead>
      <tr>
        <th style="width: 20%;">Name</th>
        <th>aktiv</th>
        <th>Fächer</th>
        <th>Studiengänge</th>
        <th>Studienabschnitte</th>
        <th>Fragen</th>
      </tr>
    </thead>
    <tbody>
      {% for testat in testate %}
      <tr>
        <td><a href="{% url 'exoral:testat-detail' testat.id %}">{{ testat.name }}</a></td>
        <td>{% if testat.active  %}✓{% else %}✗{% endif %}</td>
        <td>{{ testat.fach.all|join:", " }}</td>
        <td>{{ testat.studiengang.all|join:", " }}</td>
        <td>{{ testat.studienabschnitt.all|join:", " }}</td>
        <td>{{ testat.frage_set.count }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}